--- samples/Makefile	2023-08-14 23:46:34.000000000 -0400
+++ samples/Makefile.new	2023-12-19 11:54:43.264080087 -0500
@@ -35,13 +35,13 @@
 
 # Common includes and paths for CUDA
 ARCH ?= $(shell uname -m)
-CUDA_PATH   := /usr/local/cuda
+CUDA_PATH   := ${PREFIX}
 ifeq ($(ARCH),aarch64)
-	CUFILE_PATH ?= /usr/local/cuda/targets/sbsa-linux/lib/
-	CUFILE_INCLUDE_PATH ?= /usr/local/cuda/targets/sbsa-linux/include/
+	CUFILE_PATH ?= $(CUDA_PATH)/targets/sbsa-linux/lib/
+	CUFILE_INCLUDE_PATH ?= $(CUDA_PATH)/targets/sbsa-linux/include/
 else
-	CUFILE_PATH ?= /usr/local/cuda/targets/x86_64-linux/lib/
-	CUFILE_INCLUDE_PATH ?= /usr/local/cuda/targets/x86_64-linux/include/
+	CUFILE_PATH ?= $(CUDA_PATH)/targets/x86_64-linux/lib/
+	CUFILE_INCLUDE_PATH ?= $(CUDA_PATH)/targets/x86_64-linux/include/
 endif
 CXXFLAGS    := -Wall
 CXXFLAGS    += -I $(CUDA_PATH)/include/ 
