build_platform:
  linux_aarch64: linux_64
conda_build:
  error_overlinking: false
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
os_version:
  linux_64: cos7
  linux_aarch64: alma8
provider:
  linux_aarch64: default
